error.general: 'There was an unexpected error. Please try again later.'
